### ISSUE TITLE
Tons of issues on proxy server

### ISSUE THREAD

**Issue by anomalic1** [xtekky/gpt4free#3434]
Plan
New
Member Since
4/21/2026

Its 23rd and i am over the 24 hours quota

I get tons of issues like

data: {"error": {"message": "this event loop is already running.", "type": "api_error"}}

data: [DONE]

Created custom provider class 'G4FSpace' with base URL 'https://g4f.space/custom/srv_mm0u3dj0b6a1d9becaaf'INFO: 64.227.21.251:0 - "POST /v4/chat/completions HTTP/1.1" 200 OK 2026-04-22 08:51:29,490 | ERROR | ShadyDealer | g4f PollinationsAI error: this event loop is already running.

data: {"error": {"message": "ResponseError: Invalid G4F API key"}, "model": "claude-sonnet-4-6", "provider": "Custom"}

data: [DONE]

Even if my API key is renewed again.

Please do you have an example project on how to use g4f.dev's Arena model maybe on proxy server of mine or use it from cloud without hitting this error

Please suggest me any good API providers you have that give 0RPD or No token limits per day as Pollinations hit the pollens issue and Airforce API rpm and ollama new 300 tokens per hour

**Comment by anomalic1** [comment]
please reply

**Comment by AskingAcake** [comment]
A few separate things are happening in that report, so a clear reply could be:

1) Arena model
The g4f.dev “Arena” models (LMArena) are not meant to be used as a remote public API. They are designed for local execution through the g4f client. Running them behind a proxy server generally won’t work reliably because the Arena routing expects a local environment and internal orchestration.

2) “event loop is already running” error
That error usually happens when g4f is being called inside an already running asyncio loop (common in FastAPI, Jupyter, or threaded servers). The fix is typically to:

await the async client instead of calling sync wrappers inside async code, or
isolate g4f calls in a separate thread / worker process.
It’s not related to your API key.
3) “Invalid G4F API key”
That error comes from the custom provider you configured (https://g4f.space/...). It means the upstream provider rejected the key. Renewing the key locally doesn’t help if the upstream service has disabled it.

4) “0 RPD / unlimited tokens” providers
In practice, truly unlimited public LLM APIs don’t exist. Most services throttle sooner or later. If you need very high or uncapped usage, the realistic options are:

Self‑hosted models (Ollama + local GPU)
Ollama cloud providers like ollama.pro
Run open models on your own GPU server (vLLM, TGI, or Ollama)
Paid APIs with higher limits (OpenAI, Anthropic, etc.)
Pollinations, Airforce, and similar community gateways often rate limit or break under heavy usage.
Short answer you could send:

LMArena is limited to local execution in g4f and isn’t intended to be used as a remote API through a proxy. The “event loop is already running” error is caused by calling g4f in an existing asyncio loop, not by your API key. The new tier issue you mentioned has been fixed upstream. For higher limits you’ll need another provider or self‑hosting. You can try providers like ollama.pro or run an Ollama/vLLM instance on your own server if you want near‑unlimited usage.

**Comment by AskingAcake** [comment]
Basically, 
LMArena is limited to local execution. New tier issue is fixed. Try other providers like new ollama.pro provider

**Comment by AskingAcake** [comment]
I hope you get the point,

**Comment by anomalic1** [comment]
> I hope you get the point,

thanks for helping me out

**Comment by AskingAcake** [comment]
oh no problem dude!

**Comment by anomalic1** [comment]
> oh no problem dude!

btw do you have example python tempelates how to use ollama.pro they added recently ? cuz my response cuts off alot i dont know how to fix it
